// Drives the generic CRUD screens. Field types: text, textarea, image, number, checkbox, date, select.
export const COLLECTIONS = [
  {
    key: 'specialities',
    label: 'Specialities',
    icon: 'stethoscope',
    titleField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      {
        name: 'category',
        label: 'Service group (section on the corporate Services page & menu)',
        type: 'select',
        default: '',
        options: [
          { value: '', label: '— No group (hospital-only speciality) —' },
          'Maternity & Pregnancy',
          'Fertility & Gynaecology',
          "Children's Care",
          'Allied & Wellness',
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'icon', label: 'Icon (emoji)', type: 'text' },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'location', label: 'Shown at', type: 'location' },
      { name: 'sortOrder', label: 'Sort order', type: 'number' },
      { name: 'published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  {
    key: 'locations',
    label: 'Locations',
    icon: 'building',
    titleField: 'name',
    fields: [
      { name: 'name', label: 'Hospital name', type: 'text', required: true },
      { name: 'slug', label: 'Page URL name (e.g. "kochi" → yoursite.com/hospitals/kochi)', type: 'text' },
      { name: 'tagline', label: 'Page tagline (short sentence under the name)', type: 'text' },
      { name: 'description', label: 'About this hospital (shown on its page)', type: 'textarea', rows: 5 },
      { name: 'highlights', label: 'Highlights — one per line (e.g. "Level III NICU")', type: 'textarea', rows: 6 },
      { name: 'heroImageUrl', label: 'Page banner image', type: 'image' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'country', label: 'Country', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'mapUrl', label: 'Google Maps URL', type: 'text' },
      { name: 'website', label: 'Hospital website URL', type: 'text' },
      { name: 'websiteLabel', label: 'Website link label (e.g. "Visit kinderhospital.in →")', type: 'text' },
      { name: 'since', label: 'Tag line (e.g. "Since 2011")', type: 'text' },
      { name: 'international', label: 'International centre', type: 'checkbox', default: false },
      { name: 'imageUrl', label: 'Photo', type: 'image' },
      { name: 'sortOrder', label: 'Sort order', type: 'number' },
      { name: 'published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  {
    key: 'doctors',
    label: 'Doctors',
    icon: 'doctor',
    titleField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'speciality', label: 'Speciality', type: 'speciality' },
      { name: 'location', label: 'Location (which hospital this doctor appears on)', type: 'location' },
      { name: 'bio', label: 'Short bio (shown on cards)', type: 'textarea' },
      { name: 'fullBio', label: "Full bio (shown on the doctor's own profile page)", type: 'textarea', rows: 8 },
      { name: 'imageUrl', label: 'Photo', type: 'image' },
      { name: 'sortOrder', label: 'Sort order', type: 'number' },
      { name: 'published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  {
    key: 'testimonials',
    label: 'Testimonials',
    icon: 'chat',
    titleField: 'patientName',
    fields: [
      { name: 'patientName', label: 'Patient name', type: 'text', required: true },
      { name: 'relation', label: 'Relation / place (e.g. "Mother, Kochi")', type: 'text' },
      { name: 'quote', label: 'Quote', type: 'textarea', required: true },
      { name: 'rating', label: 'Rating (1–5)', type: 'number', default: 5 },
      { name: 'imageUrl', label: 'Photo', type: 'image' },
      { name: 'location', label: 'Shown at', type: 'location' },
      { name: 'published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  {
    key: 'news',
    label: 'News & Events',
    icon: 'news',
    titleField: 'title',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['News', 'Event', 'Camp'] },
      { name: 'excerpt', label: 'Short excerpt', type: 'textarea' },
      { name: 'body', label: 'Full article', type: 'textarea', rows: 8 },
      { name: 'imageUrl', label: 'Cover image', type: 'image' },
      { name: 'author', label: 'Author (e.g. Dr. Sreeja Rani V R)', type: 'text' },
      { name: 'location', label: 'Shown at', type: 'location' },
      { name: 'publishedAt', label: 'Publish date', type: 'date' },
      { name: 'published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
  {
    key: 'procedures',
    label: 'Procedures',
    icon: 'activity',
    titleField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'icon', label: 'Icon name (ivf, plus-circle, waves, pulse, clipboard, shield-check)', type: 'text' },
      { name: 'location', label: 'Shown at', type: 'location' },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'sortOrder', label: 'Sort order', type: 'number' },
      { name: 'published', label: 'Published', type: 'checkbox', default: true },
    ],
  },
];

export const SETTING_FIELDS = [
  { name: 'siteName', label: 'Site name', type: 'text' },
  { name: 'tagline', label: 'Tagline', type: 'text' },
  { name: 'helplinePhone', label: 'Helpline phone', type: 'text' },
  { name: 'emergencyPhone', label: 'Emergency phone', type: 'text' },
  { name: 'email', label: 'Contact email', type: 'text' },
  { name: 'announcement', label: 'Announcement bar (leave empty to hide)', type: 'text' },
  { name: 'heroTitle', label: 'Hero title', type: 'text' },
  { name: 'heroSubtitle', label: 'Hero subtitle', type: 'textarea' },
  { name: 'heroImageUrl', label: 'Hero image', type: 'image' },
  { name: 'logoUrl', label: 'Logo image', type: 'image' },
];
